name: inventaris_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  google_fonts: any
  get: 4.6.5
  firebase_core: 2.6.1
  firebase_auth: ^4.2.0
  firebase_auth_web: ^5.2.4
  cloud_firestore: ^4.3.1
  google_nav_bar: 5.0.6
  flutter:
    sdk: flutter
  ionicons: ^0.2.1
  icony: ^1.0.5
  iconify: ^0.0.1
  iconify_flutter: ^0.0.5
  date_time_picker: 2.1.0
  dropdown_search: ^5.0.5
  image_picker: ^0.8.6+2
  firebase_storage: ^11.0.13
  get_cli: ^1.8.1
  google_sign_in: ^5.4.3
  google_sign_in_web: ^0.10.2+1
  intl:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
