name: inventaris_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  google_fonts: any
  get: 4.6.5
  firebase_core: 2.4.1
  firebase_auth: 4.2.5
  google_nav_bar: 5.0.6
  flutter:
    sdk: flutter
  ionicons: ^0.2.1
  icony: ^1.0.5
  iconify: ^0.0.1
  iconify_flutter: ^0.0.5
  get_cli: ^1.8.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
